# Generated by Django 4.1.4 on 2023-03-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_resistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubMed', models.CharField(max_length=10, null=True)),
                ('drug', models.CharField(max_length=80, null=True)),
                ('cell_lo', models.CharField(max_length=255, null=True)),
                ('control_cl', models.CharField(max_length=100, null=True)),
                ('resistant_cl', models.CharField(max_length=100, null=True)),
                ('molecules', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('gene_id', models.CharField(max_length=100, null=True)),
                ('exp_inRes_cell', models.CharField(max_length=100, null=True)),
                ('post_tm', models.CharField(max_length=100, null=True)),
                ('driver_molecule', models.CharField(max_length=30, null=True)),
                ('exp_method', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
