# Generated by Django 4.1.4 on 2023-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_resistant', '0002_molecules'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecules',
            name='biomarker_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='molecules',
            name='fold_ratio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='molecules',
            name='pmid_marker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
