# Generated by Django 4.2.3 on 2023-08-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_resistant', '0003_molecules_biomarker_type_molecules_fold_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugs',
            old_name='tf',
            new_name='expression',
        ),
    ]
